# Generated by Django 5.2 on 2025-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_review',
            field=models.BooleanField(default=True, verbose_name='Это отзыв'),
        ),
    ]
