# Generated by Django 5.2 on 2025-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_post_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
    ]
